version: '3'

tasks:
  postgres:
    docker run --name postgres14 -p 6432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:14-alpine
    
  sqlc: 
    sqlc generate

  createdb: 
    docker exec -it postgres14 createdb --username=root --owner=root simplebank

  migrateup:
    migrate -path db/migration -database "postgres://root:secret@localhost:6432/simplebank?sslmode=disable" -verbose up {{.number}}

  migratedown:
    migrate -path db/migration -database "postgres://root:secret@localhost:6432/simplebank?sslmode=disable" -verbose down {{.number}}

  test:
    go test ./... -v -cover

  start: 
    go run main.go
  
  mock: 
    mockgen -package mockdb  -destination db/mock/store.go  github.com/meomeocoj/simplebank/db/sqlc Store