version: '3'

dotenv: ['app.env']  

tasks:
  postgres:
    docker run --name postgres14 -p 6432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:14-alpine
    
  sqlc: 
    sqlc generate

  createdb: 
    docker exec -it postgres14 createdb --username=root --owner=root simplebank

  migrateup:
    migrate -path db/migration -database $DB_SOURCE -verbose up {{.number}}

  migratedown:
    migrate -path db/migration -database $DB_SOURCE  -verbose down {{.number}}

  test:
    go test ./... -v -cover

  start-prod:
    /app/main

  start: 
    go run main.go
  
  mock: 
    mockgen -package mockdb  -destination db/mock/store.go  github.com/meomeocoj/simplebank/db/sqlc Store