apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplebank-api-deployment
  labels:
    app: simplebank-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplebank-api-deployment
  template:
    metadata:
      labels:
        app: simplebank-api-deployment
    spec:
      containers:
      - name: simplebank-api-deployment
        image: 422191248826.dkr.ecr.ap-southeast-1.amazonaws.com/simplebank:356d7022abbcf6769824e2fbb9a5382e5760d8e0-linux-arm64
        ports:
        - containerPort: 5000 